---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: henry-app
  namespace: staging
  labels:
    app: henry-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: henry-app
  template:
    metadata:
      labels:
        app: henry-app
    spec:
      containers:
      - name: henry-app
        image: kimschles/pod-info-app:0.0.5
        ports:
        - containerPort: 3000
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
